spring:
  application:
    name: gccw-assignment-zull
  profiles:
    active: local

server:
  port: 9095

zuul:
  routes:
    user:
      path: /user/**
      serviceId: gccw-assignment-user-service
    emails:
      path: /email/**
      serviceId: gccw-assignment-email-service
  host:
    connect-timeout-millis: 40000
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 35000
  ConnectTimeout: 35000
eureka:
  instance:
    prefer-ip-address: true
