FROM java:8
VOLUME /tmp/tomcat
ADD email-service-0.0.1-SNAPSHOT.jar email-docker.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/email-docker.jar", "--spring.profiles.active=test"]
