spring:
  profiles:
    active: local
  application:
    name: gccw-assignment-email-service
mjson:
  json:
    prefix: DEREKP
    suffix: DEREKS
debug: true

server:
  port: 9998

eureka:
  client:
    refreshInterval: 10s
